---
title: ""
---

<!--Add a loading bar!-->
<script src="pace.js"></script>
<link href="pace_loadbar_loading.css" rel="stylesheet" />

<!--Create a block for title and breadcrumbs to appear on same line-->
<div style="width: 100%; display: inline-block;">
<div style="float: left; ">
# Project Advisory Group Documents
</div>
<div style="float: right;">
<ol class="breadcrumb" style="background-color:white;">
  <li class="breadcrumb-item"><a href="index.html">Home</a></li>
  <li class="breadcrumb-item active">Project Advisory Group Documents</li>
</ol>
</div>
</div>
<hr class="hr-orange">

<br>

<!--Begin page content!-->

Thank you for agreeing to be on SPEEDIER's project advisory group (PAG). Documents of potential interest to the PAG are on this page to avoid sending large emails. We will post a PAG meeting agenda and list of questions to help make meetings more efficient.
<br>
Please let me know (katie.hampson@glasgow.ac.uk) if you would prefer another format, or would like additional information.

<hr class="hr-grey>

<div style="display: inline-block; ">

Project background: `r PHL_embed_file(filename="pag_docs/SPEEDIER Blurb", filetype="pdf", label="project summary")`  
Update on progress: `r PHL_embed_file(filename="pag_docs/2019 MAY SPEEDIER Flash Report_final", filetype="pdf", label="Flash report May 2019")`  
Approved Ethics protocol (phase 1 & 2a): `r PHL_embed_file(filename="pag_docs/Appendix 1_Protocol_v4_all", filetype="pdf", label="RITM IRB application")`  
IBCM materials: `r PHL_embed_file(filename="pag_docs/SPEEDIER IBCM Field Operations Manual", filetype="pdf", label="Field Operations Manual")` & `r PHL_embed_file(filename="pag_docs/SPEEDIER Training Programme for trainees", filetype="pdf", label="Training Programme")`  

</div>
