---
title: ""
---

## Plot Testing  

<br>

### Romblon plots {.tabset}

#### Treatment (Annual)

```{r, echo=FALSE, message=FALSE, warning=FALSE}
PHL_incidence_plot(province="Romblon", timeframe="Year", type="treatment")
```

***

#### Treatment (Quarterly)

```{r, echo=FALSE, message=FALSE, warning=FALSE}
PHL_incidence_plot(province="Romblon", timeframe="Quarterly", type="treatment")
```

***

#### Biting animal (Annual)

<div style="float: left; width: 50%">

```{r, echo=FALSE, message=FALSE, warning=FALSE}
PHL_incidence_plot(province="Romblon", timeframe="Year", type="biter")
```

</div>

<div style="float: right; width: 50%">

```{r, echo=FALSE, message=FALSE, warning=FALSE}
PHL_incidence_plot(province="Romblon", timeframe="Year", type="biter", by_p=TRUE)
```

</div>

***

#### Biting animal (Quarterly)

<div style="float: left; width: 50%">

```{r, echo=FALSE, message=FALSE, warning=FALSE}
PHL_incidence_plot(province="Romblon", timeframe="Quarterly", type="biter")
```

</div>

<div style="float: right; width: 50%">

```{r, echo=FALSE, message=FALSE, warning=FALSE}
PHL_incidence_plot(province="Romblon", timeframe="Quarterly", type="biter", by_p=TRUE)
```

</div>

***

<br>

### Population map  
  
```{r droplink, echo=FALSE, message=FALSE, warning=FALSE}
# Create table
table_site <- c("html/municipality_pop_map_2018.html",
                "html/village_pop_map_2018.html")
names(table_site) <- c("Municipality", "Barangay")

bsselect(table_site, type = "iframe", frame_height=550, style="btn-primary", show_tick=TRUE, height=0)
```
